version: '3.8'

services:
  ambev.developerevaluation.webapi:
    container_name: ambev_developer_evaluation_webapi
    image: ${DOCKER_REGISTRY-}ambevdeveloperevaluationwebapi
    build:
      context: .
      dockerfile: src/Ambev.DeveloperEvaluation.WebApi/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=ambev.developerevaluation.database;Port=5432;Database=developer_evaluation;Username=developer;Password=ev@luAt10n
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_URLS=http://+:8080
      - DOTNET_ENVIRONMENT=Development
      - Logging__LogLevel__Default=Debug
      - Logging__LogLevel__Microsoft=Information
      - Logging__LogLevel__System=Information
    ports:
      - "8080:8080"
    # Remover volumes problemáticos temporariamente
    volumes:
     - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
     - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - ambev.developerevaluation.database
      - ambev.developerevaluation.nosql
      - ambev.developerevaluation.cache
    command: >
      sh -c "
        echo 'Aguardando PostgreSQL...';
        while ! nc -z ambev.developerevaluation.database 5432; do
          sleep 1;
        done;
        echo 'PostgreSQL está pronto!';
        
        echo 'Aguardando MongoDB...';
        while ! nc -z ambev.developerevaluation.nosql 27017; do
          sleep 1;
        done;
        echo 'MongoDB está pronto!';
        
        echo 'Aguardando Redis...';
        while ! nc -z ambev.developerevaluation.cache 6379; do
          sleep 1;
        done;
        echo 'Redis está pronto!';
        
        echo 'Iniciando aplicação...';
        dotnet Ambev.DeveloperEvaluation.WebApi.dll
      "
    restart: unless-stopped

  ambev.developerevaluation.database:
    container_name: ambev_developer_evaluation_database
    image: postgres:13
    environment:
      POSTGRES_DB: developer_evaluation
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: ev@luAt10n
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  ambev.developerevaluation.nosql:
    container_name: ambev_developer_evaluation_nosql
    image: mongo:8.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: developer
      MONGO_INITDB_ROOT_PASSWORD: ev@luAt10n
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  ambev.developerevaluation.cache:
    container_name: ambev_developer_evaluation_cache
    image: redis:7.4.1-alpine
    command: redis-server --requirepass ev@luAt10n
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  mongo_data:
  redis_data: